"""empty message

Revision ID: 126b18b0022b
Revises: b40c02413ca4
Create Date: 2024-09-27 12:09:00.524597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126b18b0022b'
down_revision = 'b40c02413ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name=op.f('fk_calendar_relationships_calendar_id_calendars')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_relationships_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_calendars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_calendars',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('permission', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('calendar_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name='fk_user_calendars_calendar_id_calendars'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_calendars_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('calendar_relationships')
    # ### end Alembic commands ###
