"""empty message

Revision ID: 211b365bc855
Revises: 
Create Date: 2024-09-23 08:27:10.432908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211b365bc855'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name=op.f('fk_notes_calendar_id_calendars')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_calendars',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name=op.f('fk_user_calendars_calendar_id_calendars')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_calendars_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'calendar_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_calendars')
    op.drop_table('notes')
    op.drop_table('users')
    op.drop_table('calendars')
    # ### end Alembic commands ###
