"""empty message

Revision ID: f4111094a0f4
Revises: 9b233f3c5e7c
Create Date: 2024-09-17 11:28:19.440055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4111094a0f4'
down_revision = '9b233f3c5e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('repeating', sa.VARCHAR(), nullable=True),
    sa.Column('calendar_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name='fk_reminders_calendar_id_calendars'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
